/**
 * Constantes pour les actions d'audit
 * Permet de standardiser les noms des actions dans les logs
 */

const AUDIT_ACTIONS = {
  // ============ AUTHENTIFICATION ============
  AUTH: {
    LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
    LOGOUT: 'AUTH_LOGOUT',
    CODE_RESENT: 'AUTH_CODE_RESENT',
    CODE_EXPIRED: 'AUTH_CODE_EXPIRED',
    TOKEN_REFRESH: 'AUTH_TOKEN_REFRESH',
  },

  // ============ UTILISATEURS ============
  USER: {
    CREATED: 'USER_CREATED',
    UPDATED: 'USER_UPDATED',
    DELETED: 'USER_DELETED',
    PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
    ROLE_CHANGED: 'USER_ROLE_CHANGED',
    VIEWED: 'USER_VIEWED',
    LIST_VIEWED: 'USER_LIST_VIEWED',
  },

  // ============ ÉLECTIONS ============
  ELECTION: {
    CREATED: 'ELECTION_CREATED',
    UPDATED: 'ELECTION_UPDATED',
    DELETED: 'ELECTION_DELETED',
    STATUS_CHANGED: 'ELECTION_STATUS_CHANGED',
    VIEWED: 'ELECTION_VIEWED',
    LIST_VIEWED: 'ELECTION_LIST_VIEWED',
  },

  // ============ RÉSULTATS SAISIS ============
  RESULT: {
    CREATED: 'RESULT_CREATED',
    UPDATED: 'RESULT_UPDATED',
    DELETED: 'RESULT_DELETED',
    VALIDATED: 'RESULT_VALIDATED',
    REJECTED: 'RESULT_REJECTED',
    VIEWED: 'RESULT_VIEWED',
    LIST_VIEWED: 'RESULT_LIST_VIEWED',
  },

  // ============ RÉSULTATS PARTIS ============
  RESULT_PARTI: {
    CREATED: 'RESULT_PARTI_CREATED',
    UPDATED: 'RESULT_PARTI_UPDATED',
    DELETED: 'RESULT_PARTI_DELETED',
    BULK_CREATED: 'RESULT_PARTI_BULK_CREATED',
  },

  // ============ COMPILATIONS ============
  COMPILATION: {
    CREATED: 'COMPILATION_CREATED',
    UPDATED: 'COMPILATION_UPDATED',
    DELETED: 'COMPILATION_DELETED',
    VALIDATED: 'COMPILATION_VALIDATED',
    REJECTED: 'COMPILATION_REJECTED',
    OBSERVATION_SET: 'COMPILATION_OBSERVATION_SET',
    VIEWED: 'COMPILATION_VIEWED',
    LIST_VIEWED: 'COMPILATION_LIST_VIEWED',
  },

  // ============ RÉCAPITULATIFS ÉLECTORAUX ============
  RECAP: {
    CREATED: 'RECAP_CREATED',
    UPDATED: 'RECAP_UPDATED',
    DELETED: 'RECAP_DELETED',
    VIEWED: 'RECAP_VIEWED',
    LIST_VIEWED: 'RECAP_LIST_VIEWED',
  },

  // ============ PARTIS ============
  PARTI: {
    CREATED: 'PARTI_CREATED',
    UPDATED: 'PARTI_UPDATED',
    DELETED: 'PARTI_DELETED',
    VIEWED: 'PARTI_VIEWED',
    LIST_VIEWED: 'PARTI_LIST_VIEWED',
  },

  // ============ GÉOGRAPHIE ============
  GEO: {
    DEPARTEMENT_CREATED: 'GEO_DEPARTEMENT_CREATED',
    DEPARTEMENT_UPDATED: 'GEO_DEPARTEMENT_UPDATED',
    DEPARTEMENT_DELETED: 'GEO_DEPARTEMENT_DELETED',
    COMMUNE_CREATED: 'GEO_COMMUNE_CREATED',
    COMMUNE_UPDATED: 'GEO_COMMUNE_UPDATED',
    COMMUNE_DELETED: 'GEO_COMMUNE_DELETED',
    CIRCONSCRIPTION_CREATED: 'GEO_CIRCONSCRIPTION_CREATED',
    CIRCONSCRIPTION_UPDATED: 'GEO_CIRCONSCRIPTION_UPDATED',
    CIRCONSCRIPTION_DELETED: 'GEO_CIRCONSCRIPTION_DELETED',
    ARRONDISSEMENT_CREATED: 'GEO_ARRONDISSEMENT_CREATED',
    ARRONDISSEMENT_UPDATED: 'GEO_ARRONDISSEMENT_UPDATED',
    ARRONDISSEMENT_DELETED: 'GEO_ARRONDISSEMENT_DELETED',
    QUARTIER_CREATED: 'GEO_QUARTIER_CREATED',
    QUARTIER_UPDATED: 'GEO_QUARTIER_UPDATED',
    QUARTIER_DELETED: 'GEO_QUARTIER_DELETED',
  },

  // ============ CENTRES DE VOTE ============
  CENTRE: {
    CREATED: 'CENTRE_CREATED',
    UPDATED: 'CENTRE_UPDATED',
    DELETED: 'CENTRE_DELETED',
    VIEWED: 'CENTRE_VIEWED',
    LIST_VIEWED: 'CENTRE_LIST_VIEWED',
  },

  // ============ POSTES DE VOTE ============
  POSTE: {
    CREATED: 'POSTE_CREATED',
    UPDATED: 'POSTE_UPDATED',
    DELETED: 'POSTE_DELETED',
    VIEWED: 'POSTE_VIEWED',
    LIST_VIEWED: 'POSTE_LIST_VIEWED',
  },

  // ============ FICHIERS / UPLOADS ============
  FILE: {
    UPLOADED: 'FILE_UPLOADED',
    DELETED: 'FILE_DELETED',
    DOWNLOADED: 'FILE_DOWNLOADED',
  },

  // ============ ADMIN / SYSTÈME ============
  SYSTEM: {
    STATS_VIEWED: 'SYSTEM_STATS_VIEWED',
    EXPORT_DATA: 'SYSTEM_EXPORT_DATA',
    IMPORT_DATA: 'SYSTEM_IMPORT_DATA',
    CONFIG_CHANGED: 'SYSTEM_CONFIG_CHANGED',
  },
};

// Resources pour identifier le type d'entité concernée
const RESOURCES = {
  USER: 'User',
  ELECTION: 'Election',
  RESULT_SAISI: 'ResultSaisi',
  RESULT_PARTI: 'ResultatParti',
  COMPILATION: 'Compilation',
  RECAP: 'RecapitulatifElectoral',
  PARTI: 'Parti',
  DEPARTEMENT: 'Departement',
  COMMUNE: 'Commune',
  CIRCONSCRIPTION: 'Circonscription',
  ARRONDISSEMENT: 'Arrondissement',
  QUARTIER: 'Quartier',
  CENTRE_DE_VOTE: 'CentreDeVote',
  POSTE_DE_VOTE: 'PosteDeVote',
  FILE: 'File',
  AUTH: 'Auth',
};

module.exports = {
  AUDIT_ACTIONS,
  RESOURCES,
};
