// ============ DONNÉES COMPLÈTES COTONOU ============
// Structure: { arrondissement: [{ q: quartier, c: [{ n: nom_centre, p: postes }] }] }

module.exports = {
  '01': [
    { q: 'Avotrou AIMONLONFIDE', c: [{ n: 'CENTRE DE SANTE AVOTROU', p: 8 }, { n: 'CS LES PREMICES', p: 3 }] },
    { q: 'AVOTROU GBEGO', c: [{ n: 'CS LA GRACE', p: 3 }, { n: 'EPP AVOTROU', p: 7 }] },
    { q: 'AVOTROU HOUEZEKOME', c: [{ n: 'ECOLE MATERNELLE HOUEZEKOME', p: 5 }] },
    { q: 'DANDJI', c: [{ n: 'ECOLE PRIVEE LE BERGER', p: 5 }, { n: 'EPP DANDJI', p: 8 }] },
    { q: 'DANDJI HOKANME', c: [{ n: 'EPP DANDJI HOKANME', p: 3 }] },
    { q: 'DONATEN', c: [{ n: 'EPP DONATEN', p: 7 }] },
    { q: 'FINAGNON', c: [{ n: 'CEG LE LITTORAL G/A', p: 4 }, { n: 'EPP FINAGNON', p: 3 }] },
    { q: 'N\'VENAMEDE', c: [{ n: 'EPP N\'VENAMEDE', p: 5 }] },
    { q: 'SURU LERE', c: [{ n: 'EPP SURU LERE', p: 7 }, { n: 'ESEP LE BON BERGER', p: 3 }] },
    { q: 'TANTO', c: [{ n: 'EPP TANTO', p: 8 }] },
    { q: 'TCHANHOUNKPAME', c: [{ n: 'EPP TCHANHOUNKPAME', p: 5 }] },
    { q: 'TOKPLEGBE', c: [{ n: 'CEG LITTORAL G/B', p: 6 }, { n: 'CS SAINTE THERESE D\'AVILA', p: 2 }, { n: 'EPP TOKPLEGBE', p: 2 }] },
    { q: 'YAGBE', c: [{ n: 'COMPLEXE SCOLAIRE YAGBE', p: 8 }] },
  ],
  '02': [
    { q: 'AHOUASSA', c: [{ n: 'EPP AHOUASSA KOWEGBO', p: 5 }] },
    { q: 'DJEDJE-LAYE', c: [{ n: 'EPP DJEDJE-LAYE', p: 5 }] },
    { q: 'GANKPODO', c: [{ n: 'EPP GANKPODO', p: 6 }, { n: 'MAISON DES JEUNES DE GANKPODO', p: 3 }] },
    { q: 'IREDE', c: [{ n: 'EPP IREDE', p: 8 }] },
    { q: 'KOWEGBO', c: [{ n: 'EPP AHOUASSA KOWEGBO', p: 8 }] },
    { q: 'KPONDEHOU', c: [{ n: 'COMPLEXE SCOLAIRE KPONDEHOU', p: 8 }, { n: 'ECOLE PRIMAIRE PRIVEE LE LAROUSSE', p: 3 }] },
    { q: 'KPONDEHOU TCHEME', c: [{ n: 'LYCEE TECHNIQUE ET PROFESSIONNEL KPONDEHOU TCHEME', p: 3 }] },
    { q: 'LOM-NAVA', c: [{ n: 'EPP LOM-NAVA', p: 5 }] },
    { q: 'MINONTCHOU', c: [{ n: 'COMPLEXE SCOLAIRE LA PROVIDENCE', p: 3 }, { n: 'EPP MINONTCHOU', p: 6 }] },
    { q: 'SENADE SEKOU', c: [{ n: 'EPP SENADE SEKOU', p: 4 }] },
    { q: 'SENANDE', c: [{ n: 'CS SENA EN FACE DE LA SBEE SENADE', p: 3 }, { n: 'EPP SENANDE', p: 7 }] },
    { q: 'YENAWA', c: [{ n: 'COMPLEXE SCOLAIRE YENAWA', p: 10 }, { n: 'ECOLE PRIMAIRE PRIVEE ST JEAN-BAPTISTE', p: 5 }] },
    { q: 'YENAWA DAHO', c: [{ n: 'EPP YENAWA DAHO', p: 4 }] },
  ],
  '03': [
    { q: 'ADJEGOUNLE', c: [{ n: 'EPP DAZAN NOUVEL HORIZON', p: 4 }] },
    { q: 'ADOGLETA', c: [{ n: 'EPP ADOGLETA', p: 6 }, { n: 'EPP LA RELANCE D\'ADOGLETA', p: 4 }] },
    { q: 'AGBATO', c: [{ n: 'EM MADJA', p: 8 }, { n: 'EPP AGBATO', p: 5 }] },
    { q: 'AGBODJEDO', c: [{ n: 'ECOLE LES PALMIERS', p: 5 }, { n: 'EPP LE LAC AGBODJEDO', p: 8 }] },
    { q: 'AYELAWADJE', c: [{ n: 'COLLEGE LUCIE VERONE', p: 6 }, { n: 'EPP AYELAWADJE', p: 3 }] },
    { q: 'AYELAWADJE AGONGBOME', c: [{ n: 'EPP AYELAWADJE AGONGBOME', p: 6 }] },
    { q: 'FIFATIN', c: [{ n: 'EPP FIFATIN', p: 4 }] },
    { q: 'GBENONKPO', c: [{ n: 'ECOLE CATHOLIQUE SACRE-COEUR', p: 4 }] },
    { q: 'HLACOMEY', c: [{ n: 'EPP HLACOMEY', p: 6 }, { n: 'EPP SAINTE EUNICE DE HLACOMEY', p: 3 }] },
    { q: 'KPANKPAN', c: [{ n: 'COMPLEXE SCOLAIRE KPANKPAN', p: 7 }] },
    { q: 'MIDOMBO', c: [{ n: 'EPP AKPAKPA NORD', p: 8 }, { n: 'EPP MIDOMBO', p: 3 }] },
    { q: 'SEGBEYA NORD', c: [{ n: 'ECOLE PRIMAIRE PRIVEE LE VERGER', p: 6 }, { n: 'EPP SEGBEYA NORD', p: 2 }] },
    { q: 'SEGBEYA SUD', c: [{ n: 'CEG SEGBEYA', p: 7 }] },
  ],
  '04': [
    { q: 'ABOKICODJI CENTRE', c: [{ n: 'COMPLEXE SCOLAIRE PROTESTANT BETHANIE', p: 5 }] },
    { q: 'ABOKICODJI LAGUNE', c: [{ n: 'DIRECTION DES PECHES (MAEP)', p: 4 }] },
    { q: 'AKPAKPA DODOME', c: [{ n: 'EPP ENAGNON', p: 8 }] },
    { q: 'DEDOKPO', c: [{ n: 'ECOLE MATERNELLE DEDOKPO', p: 5 }, { n: 'EPP DEDOKPO', p: 4 }] },
    { q: 'ENAGNON', c: [{ n: 'EPP ENAGNON', p: 6 }, { n: 'MAISON DES JEUNES', p: 2 }] },
    { q: 'FIFADJI HOUTO', c: [{ n: 'DIRECTION DES TRANSPORTS TERRESTRES (DTT)', p: 3 }, { n: 'EPP FIFADJI HOUTO', p: 2 }] },
    { q: 'GBEDJEWIN', c: [{ n: 'CENTRE DE PROMOTION SOCIALE DE COTONOU AKPAKPA', p: 3 }, { n: 'ECOLE MATERNELLE GBEDJEWIN', p: 1 }] },
    { q: 'MISSESSIN', c: [{ n: 'BUREAU DE L\'ARRONDISSEMENT', p: 4 }, { n: 'EPP AKPAKPA MARCHE', p: 2 }] },
    { q: 'OHE', c: [{ n: 'ECOLE MATERNELLE PUBLIQUE HABITAT', p: 3 }, { n: 'EPP RENE PLEVEN', p: 1 }] },
    { q: 'SODJEATINME CENTRE', c: [{ n: 'CINEMA CONCORDE', p: 4 }] },
    { q: 'SODJEATINME EST', c: [{ n: 'CPPE', p: 4 }] },
    { q: 'SODJEATINME OUEST', c: [{ n: 'EPP AKPAKPA EX-REGIONAL', p: 4 }] },
  ],
  '05': [
    { q: 'AVLEKETE JONQUET', c: [{ n: 'EX-GARE JONQUET UNACOB', p: 3 }] },
    { q: 'BOCOSSI TOKPA', c: [{ n: 'EPP NOUVEAU PONT', p: 2 }] },
    { q: 'DOTA', c: [{ n: 'ECOLE FRANCO-ARABE', p: 2 }] },
    { q: 'GBEDOKPO', c: [{ n: 'CS GBETO SUD PARTIES B ET C', p: 3 }] },
    { q: 'GBETO', c: [{ n: 'ECOLE MATERNELLE PUBLIQUE GBETO', p: 4 }] },
    { q: 'GUINKOMEY', c: [{ n: 'ECOLE URBAINE CENTRE PARTIE A', p: 3 }] },
    { q: 'MIFONGOU', c: [{ n: 'ECOLE JULES FERRY', p: 3 }] },
    { q: 'MISSEBO', c: [{ n: 'LYCEE TECHNIQUE COULYBALI', p: 4 }] },
    { q: 'MISSITE', c: [{ n: 'COMPLEXE SCOLAIRE GBETO-SUD PARTIE B', p: 3 }] },
    { q: 'NOUVEAU PONT', c: [{ n: 'ECOLE MATERNELLE GBOGBANOU', p: 2 }] },
    { q: 'TOKPA HOHO', c: [{ n: 'ECOLE URBAINE CENTRE PARTIE B', p: 3 }] },
    { q: 'XWLACODJI KPODJI', c: [{ n: 'EPP XWLACODJI G/A', p: 3 }] },
    { q: 'XWLACODJI PLAGE', c: [{ n: 'EPP XWLACODJI G/B ET C', p: 6 }] },
    { q: 'ZONGO EHUZU', c: [{ n: 'EPP CHARLES GUILLOT', p: 5 }] },
    { q: 'ZONGO NIMA', c: [{ n: 'ECOLE CHARLES GUILLOT', p: 4 }] },
  ],
  '06': [
    { q: 'AHOUANSORI AGATA', c: [{ n: 'COMPLEXE SCOLAIRE LA CAPUCINE', p: 5 }, { n: 'EPP GBEFFA', p: 2 }] },
    { q: 'AHOUANSORI AGUE', c: [{ n: 'CEG LE LAC PARTIE A', p: 5 }] },
    { q: 'AHOUANSORI LADJI', c: [{ n: 'EPP LADJI', p: 9 }] },
    { q: 'AHOUANSORI TOWETA', c: [{ n: 'CEG LE LAC PARTIE B', p: 8 }, { n: 'COMPLEXE SCOLAIRE LA PRECISION', p: 3 }] },
    { q: 'AHOUANSORI TOWETA KPOTA', c: [{ n: 'ECOLE CATHOLIQUE STE CECILE', p: 5 }] },
    { q: 'AIDJEDO', c: [{ n: 'EPP ST LOUIS (EX ST CYRILLE)', p: 6 }] },
    { q: 'AIDJEDO AHITO', c: [{ n: 'EPP DEO GRACIAS', p: 5 }] },
    { q: 'AIDJEDO GBEGO', c: [{ n: 'EPP JERICHO', p: 6 }] },
    { q: 'AIDJEDO VIGNON', c: [{ n: 'ECOLE MATERNELLE BILINGUE', p: 3 }, { n: 'EPP LA MACEDOINE', p: 1 }, { n: 'EPP YEMON LE PRINCE', p: 3 }] },
    { q: 'DANTOKPA', c: [{ n: 'CEG DANTOKPA', p: 4 }] },
    { q: 'DJIDJE', c: [{ n: 'ANNEXE CS L\'INTELLIGENT', p: 4 }, { n: 'COMPLEXE SCOLAIRE LA SONNETTE', p: 6 }, { n: 'COMPLEXE SCOLAIRE L\'INTELLIGENT', p: 3 }] },
    { q: 'DJIDJE AICHEDJI', c: [{ n: 'EPP DJIDJE', p: 6 }] },
    { q: 'GBEDJROMEDE', c: [{ n: 'CS ABERE', p: 5 }, { n: 'CS LE MERITE PLUS', p: 3 }, { n: 'ECOLE MATERNELLE AHOUANSORI AGUE', p: 3 }] },
    { q: 'GBEDJROMEDE SUD', c: [{ n: 'COLLEGE LA REFERENCE', p: 5 }] },
    { q: 'HINDE NORD', c: [{ n: 'EPP ANIHUVI', p: 5 }, { n: 'EPP HINDE NORD', p: 2 }] },
    { q: 'HINDE SUD', c: [{ n: 'ANNEXE COMPLEXE SCOLAIRE LA SONNETTE', p: 4 }, { n: 'COMPLEXE HINDE SUD', p: 3 }, { n: 'CS HINDE SUD', p: 1 }] },
    { q: 'JERICHO NORD', c: [{ n: 'COLLEGE BON BERGER', p: 5 }, { n: 'GROUPE SCOLAIRE LE BERGER FIDELE', p: 1 }] },
    { q: 'JERICHO SUD', c: [{ n: 'GROUPE SCOLAIRE LA SYNAGOGUE', p: 3 }, { n: 'KING COLLEGE COTONOU', p: 1 }] },
    { q: 'VOSSA', c: [{ n: 'CENTRE DE SANTE EMMANUEL VOSSA', p: 4 }] },
  ],
  '07': [
    { q: 'DAGBEDJI SIKE', c: [{ n: 'EPP SIKE-SUD PARTIE A', p: 3 }] },
    { q: 'ENAGNON-SIKE', c: [{ n: 'EPP SIKE-SUD PARTIE B', p: 6 }] },
    { q: 'FIGNON SIKE', c: [{ n: 'EPP EVEIL ET VIE', p: 6 }] },
    { q: 'GBEDOMIDJI', c: [{ n: 'COURS SECONDAIRE PROTESTANT', p: 5 }] },
    { q: 'GBENAN', c: [{ n: 'EPP CSP', p: 4 }, { n: 'EPP LA SOURCE', p: 1 }] },
    { q: 'MISSITE-SIKE', c: [{ n: 'EPP SIKE 3 G/A ET B', p: 6 }] },
    { q: 'SEDAMI', c: [{ n: 'ECOLE MATERNELLE SAINT MICHEL DE GBEWA', p: 1 }, { n: 'ECOLE PRIVEE DE SOUZA 1', p: 3 }, { n: 'ECOLE PRIVEE DE SOUZA 2', p: 3 }] },
    { q: 'SEDJRO SAINT MICHEL', c: [{ n: 'ECOLE CATHOLIQUE ST MICHEL', p: 4 }, { n: 'ECOLE PRIVEE CATHOLIQUE ST AUGUSTIN', p: 1 }] },
    { q: 'SEHOGAN SIKE', c: [{ n: 'EPP SEHOGAN', p: 4 }] },
    { q: 'TODOTE', c: [{ n: 'EPP ST JEAN 3 PARTIE A', p: 2 }] },
    { q: 'YEVEDO', c: [{ n: 'EPP ST JEAN 3 PARTIE B', p: 3 }] },
  ],
  '08': [
    { q: 'AGBONDJEDO', c: [{ n: 'COMPLEXE SCOLAIRE PRIVE BAPTISTE', p: 10 }] },
    { q: 'AGONTINKON', c: [{ n: 'ECOLE PRIVEE HARMONIE', p: 7 }] },
    { q: 'GBEDAGBA', c: [{ n: 'COMPLEXE POLYTECHNIQUE SAINT YVES', p: 5 }, { n: 'EPP GBEDAGBA', p: 5 }] },
    { q: 'HOUEHOUN', c: [{ n: 'COMPLEXE POLYTECHNIQUE DE GESTION ET DE SECRETARIAT PRIVEE (CPGS)', p: 2 }, { n: 'ECOLE PRIVEE NAGUEZE', p: 3 }] },
    { q: 'HOUENOUSSOU STE RITA', c: [{ n: 'ECOLE MATERNELLE DE HOUENOUSSOU STE RITA', p: 3 }, { n: 'EP COEUR SACRE DE JESUS', p: 4 }] },
    { q: 'MEDEDJRO', c: [{ n: 'EPP MEDEDJRO', p: 3 }] },
    { q: 'MINONKPO WOLOGUEDE', c: [{ n: 'CEG SAINTE RITA', p: 6 }, { n: 'EPP SIKE-NORD', p: 3 }] },
    { q: 'TONATO', c: [{ n: 'ECOLE PRIVEE SALANON', p: 4 }, { n: 'EPP TONATO', p: 5 }] },
  ],
  '09': [
    { q: 'FIFADJI', c: [{ n: 'CS SAINTE FACE', p: 3 }, { n: 'ECOLE MATERNELLE DE FIFADJI', p: 7 }, { n: 'EPP FIFADJI G/D-E', p: 4 }, { n: 'SIEGE 9EME ARRONDISSEMENT', p: 5 }] },
    { q: 'KINDONOU', c: [{ n: 'CEG LE NOKOUE', p: 8 }, { n: 'ECOLE PRIVEE SAINTE HELENE DE CASTOR', p: 4 }, { n: 'EPP MENONTIN NORD G/A-B', p: 5 }] },
    { q: 'MENONTIN', c: [{ n: 'COLLEGE MARTIN LUTHER KING', p: 11 }, { n: 'EPP MENONTIN SUD G/A-B-C-D', p: 8 }] },
    { q: 'VOSSA-KPODJI', c: [{ n: 'EPP VOSSA-KPODJI', p: 6 }] },
    { q: 'ZOGBO', c: [{ n: 'CEG ZOGBO', p: 8 }, { n: 'COLLEGE PYTAGHORE', p: 4 }, { n: 'EPP ZOGBO G/A, B, C ET D', p: 7 }] },
    { q: 'ZOGBOHOUE', c: [{ n: 'COLLEGE HOUPHOUËT BOIGNY', p: 10 }, { n: 'COMPLEXE EMILIE DE VILLENEUVE', p: 3 }, { n: 'EPP ZOGBOHOUE', p: 4 }] },
  ],
  '10': [
    { q: 'AGOUNVOCODJI', c: [{ n: 'EPP GBEMA', p: 4 }, { n: 'EPP ST GERARD MAGELLAN', p: 3 }] },
    { q: 'GBENONKPO', c: [{ n: 'EPP ST LAZARRE', p: 2 }, { n: 'EPP VEDOKO 2', p: 4 }] },
    { q: 'KOUHOUNOU', c: [{ n: 'EPP PAULINE KERGOMARD', p: 5 }, { n: 'EPP SETOVI G/A ET B', p: 2 }] },
    { q: 'MIDEDJI', c: [{ n: 'EPP VEDOKO 3 G/A ET B', p: 6 }] },
    { q: 'MISSEKPLE', c: [{ n: 'EPP DOMINGO', p: 6 }, { n: 'EPP ETINCELLE DIVINE', p: 2 }] },
    { q: 'MISSOGBE', c: [{ n: 'ECOLE DES SOURDS', p: 4 }, { n: 'EPP LA TUTRICE', p: 1 }] },
    { q: 'SETOVI', c: [{ n: 'EPP SETOVI 2', p: 5 }] },
    { q: 'VEDOKO', c: [{ n: 'CEG VEDOKO', p: 8 }, { n: 'ECOLE MATERNELLE VEDOKO 1', p: 2 }, { n: 'EPP VEDOKO 1', p: 5 }] },
    { q: 'YENAWA-FIFADJI', c: [{ n: 'EPP FIFADJI', p: 6 }] },
  ],
  '11': [
    { q: 'GBEDIGA GUEDEHOUNGUE', c: [{ n: 'CEG GBEGAMEY', p: 3 }] },
    { q: 'GBEGAMEY AHITO', c: [{ n: 'COMPLEXE SCOLAIRE GBEGAMEY 1', p: 5 }] },
    { q: 'GBEGAMEY CENTRE', c: [{ n: 'EPP GBEGAMEY 2', p: 8 }] },
    { q: 'GBEGAMEY DODO AYIDJE', c: [{ n: 'ECOLE NATIONALE D\'ECONOMIE APPLIQUEE ET DE MANAGEMENT (ENEAM)', p: 4 }] },
    { q: 'GBEGAMEY GBAGOUDO', c: [{ n: 'EPP AGONDJA TOFFIN', p: 4 }, { n: 'EPP ST JEAN GBAGOUDO', p: 2 }] },
    { q: 'GBEGAMEY MIFONGOU', c: [{ n: 'COMPLEXE SCOLAIRE GBEGAMEY SUD', p: 4 }, { n: 'EPP ST JEAN 1', p: 1 }] },
    { q: 'HOUEYIHO', c: [{ n: 'COMPLEXE SCOLAIRE HOUEYIHO', p: 4 }, { n: 'ECOLE MATERNELLE HOUEYIHO', p: 2 }] },
    { q: 'HOUEYIHO TANOU', c: [{ n: 'EPP HOUEYIHO 2', p: 8 }] },
    { q: 'SAINT JEAN GBEDIGA', c: [{ n: 'ECOLE CATHOLIQUE ST JEAN', p: 5 }] },
    { q: 'VODJE ALLOBATIN', c: [{ n: 'EPP YAMADJAKO', p: 3 }] },
    { q: 'VODJE AYIDOTE', c: [{ n: 'COLLEGE MEGAN', p: 3 }] },
    { q: 'VODJE CENTRE', c: [{ n: 'EPP VODJE SUD', p: 6 }] },
    { q: 'VODJE FINAGNON', c: [{ n: 'EPP VODJE NORD', p: 4 }] },
  ],
  '12': [
    { q: 'AHOUANLEKO', c: [{ n: 'CNHU', p: 3 }, { n: 'COLLEGE PERE AUPIAIS', p: 2 }] },
    { q: 'AIBATIN DODO', c: [{ n: 'EPP ETOILE DU MATIN', p: 6 }, { n: 'EPP LE ROCHER', p: 1 }] },
    { q: 'AKOGBATO', c: [{ n: 'ECOLE PRIVEE AUBERGINE DU GOLF', p: 4 }, { n: 'EPP AKOGBATO G/A-B', p: 9 }, { n: 'EPP LA PERFORMANCE', p: 4 }, { n: 'EPP LES COCOTERAIES', p: 5 }] },
    { q: 'CADJEHOUN AGONGA', c: [{ n: 'ECOLE MATERNELLE CADJEHOUN', p: 6 }, { n: 'EPP CADJEHOUN', p: 1 }] },
    { q: 'CADJEHOUN AUPIAIS', c: [{ n: 'ECOLE DOCTORALE (ANNEXE FASEG)', p: 3 }, { n: 'EPP GBEGAMEY NORD PARTIE C', p: 2 }] },
    { q: 'CADJEHOUN AZALOKOGON', c: [{ n: 'EPP CADJEHOUN PARTIE A', p: 7 }] },
    { q: 'CADJEHOUN DETINSA', c: [{ n: 'EPP GBEGAMEY NORD PARTIE A', p: 3 }] },
    { q: 'CADJEHOUN GARE', c: [{ n: 'EPP GBEGAMEY NORD PARTIE B', p: 4 }] },
    { q: 'CADJEHOUN KPOTA', c: [{ n: 'EPP CADJEHOUN PARTIE B', p: 4 }] },
    { q: 'FIDJROSSE CENTRE', c: [{ n: 'ECOLE MATERNELLE FIDJROSSE CENTRE', p: 10 }, { n: 'EPP FIDJROSSE CENTRE', p: 6 }, { n: 'EPP FIDJROSSE CENTRE GROUPE C', p: 4 }] },
    { q: 'FIDJROSSE KPOTA', c: [{ n: 'COMPLEXE SCOLAIRE LA COURONNE', p: 7 }, { n: 'ECOLE PRIMAIRE PRIVEE EUREKA', p: 4 }, { n: 'EPP KPOTA', p: 5 }] },
    { q: 'FIYEGNON HOUTA', c: [{ n: 'CEG FIYEGNON', p: 8 }, { n: 'EPP GRAND JACQUOT PARTIE B', p: 4 }] },
    { q: 'FIYEGNON JACQUOT', c: [{ n: 'CENTRE POLYVALENT LES METIERS', p: 5 }, { n: 'EPP GRAND JACQUOT PARTIE A', p: 3 }] },
    { q: 'GBODJETIN', c: [{ n: 'CEG ENTENTE', p: 7 }, { n: 'CS LE MERCURE', p: 3 }, { n: 'EPP GBODJETIN', p: 5 }] },
    { q: 'HAIE VIVE-COCOTIERS', c: [{ n: 'CEG OCEAN', p: 3 }, { n: 'EPP LES COCOTIERS', p: 2 }] },
    { q: 'HLAZOUNTO', c: [{ n: 'EPP GERARD DEVILLIER', p: 3 }, { n: 'EPP HLAZOUNTO', p: 8 }, { n: 'EPP JAURES CREDO', p: 3 }] },
    { q: 'VODJE KPOTA', c: [{ n: 'EPP ST BASILE', p: 5 }] },
    { q: 'YEMICODJI', c: [{ n: 'COLLEGE EL-LAMELLE', p: 4 }, { n: 'EPP TOFFA', p: 3 }] },
  ],
  '13': [
    { q: 'ADJAHA-CITE', c: [{ n: 'CENTRE VIDOMEGON', p: 5 }] },
    { q: 'AGLA-AGONGBOMEY', c: [{ n: 'CS ST JUSTIN LE PHILOSOPHE', p: 4 }, { n: 'EPP AGONGBOMEY G/A , B ET C', p: 7 }, { n: 'MAISON DES JEUNES D\'AGLA', p: 6 }] },
    { q: 'AGLA-AKPLOMEY', c: [{ n: 'ECOLE PRIVEE SACRE COEUR', p: 4 }, { n: 'EPP AKPLOMEY A, B ET C', p: 8 }] },
    { q: 'AGLA-CENTRE', c: [{ n: 'EPP AGLA-CENTRE G/A ET B', p: 6 }] },
    { q: 'AGLA-FIGARO', c: [{ n: 'EPP AGLA YOLOMAHOUTO A, B ET C', p: 6 }] },
    { q: 'AGLA-FINAFA', c: [{ n: 'ECOLE PRIVEE LAVOISIER', p: 3 }, { n: 'EPP AGLA SUD', p: 7 }] },
    { q: 'AGLA-LES PYLONES', c: [{ n: 'CEG LES PYLONES', p: 10 }, { n: 'ECOLE PRIVEE ST FRANCOIS DE SALLE', p: 3 }, { n: 'EPP AGLA-NORD G/A ET B', p: 5 }, { n: 'EPP NOTRE DAME DE LAURETTE', p: 3 }] },
    { q: 'AGLA-PETIT CHATEAU', c: [{ n: 'EPP AGLA-EST', p: 6 }] },
    { q: 'AHOGBOHOUE CITE DE L\'EXPERIENCE', c: [{ n: 'EPP AHOGBOHOUE', p: 6 }] },
    { q: 'AHOGBOHOUE CITE EUCHARISTIE', c: [{ n: 'ECOLE MATERNELLE CITE HOUEYIHO', p: 4 }] },
    { q: 'AIBATIN KPOTA', c: [{ n: 'CS ST PASCAL', p: 3 }, { n: 'EPP AIBATIN II', p: 6 }] },
    { q: 'GBEDEGBE', c: [{ n: 'BUREAU 13EME ARRONDISSEMENT', p: 6 }] },
    { q: 'HOUENOUSSOU', c: [{ n: 'CEG HOUEYIHO', p: 5 }] },
    { q: 'MISSITE', c: [{ n: 'EPP MISSITE', p: 4 }] },
  ],
};